#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus    true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Panel
/home/v/.nvm/versions/node/v14.4.0/bin/node ~/linux/bar.js | lemonbar -p -f "-etl-*-medium-*-normal-*-24-*" &

# Redshift <3
redshift-gtk &

# Key hacks
# xmodmap ~/.Xmodmap
setxkbmap -option "lv3:caps_switch"
setxkbmap -option "ctrl:swap_lalt_lctl"

# Mouse refresh rate
xset r rate 200 50

# Mouse speed
xinput set-prop "Razer Razer Abyssus 2000" "Coordinate Transformation Matrix" 0.50 0 0 0 0.50 0 0 0 1
xinput set-prop "DLL096D:01 06CB:CDE6 Touchpad" "Coordinate Transformation Matrix" 4.00 0 0 0 4.00 0 0 0 1

# Set background image
feh --bg-scale ~/Pictures/castle.jpg
